INSERT INTO MovieEntity (name,genre,date_Of_Start,date_Of_Finish,duration,picture,description,is_Active)
VALUES ('Lady Bird','drama','2017-12-17','2017-12-31',137,'bird.jpg','American comedy-drama film written and directed by Greta Gerwig and starring Saoirse Ronan, Laurie Metcalf, Tracy Letts, Lucas Hedges, Timothée Chalamet, Beanie Feldstein, Stephen McKinley Henderson, and Lois Smith. Set in Sacramento, California in 2002, it is a coming-of-age story of a high-school senior (Ronan) and her turbulent relationship with her mother (Metcalf).
Lady Bird premiered at the Telluride Film Festival on September 1, 2017 and was released in the United States on November 3, 2017 by A24. Gerwig screenplay, direction, and Ronan and Metcalf performances were praised, and it has grossed over $68 million on a $10 million budget.
Lady Bird was chosen by the National Board of Review, the American Film Institute, and Time as one of the top 10 films of the year. At the 90th Academy Awards, it earned five nominations: Best Picture, Best Actress for Ronan, Best Supporting Actress for Metcalf, Best Original Screenplay, and Best Director. At the 75th Golden Globe Awards, Lady Bird won for Best Motion Picture – Musical or Comedy and Best Actress – Motion Picture Musical or Comedy (Ronan), and was nominated for two more. It was also nominated for three British Academy Film Awards.',0),
  ('Black panther','adventure','2018-01-25','2018-02-15',134,'panther.jpg','Centuries ago, five African tribes war over a meteorite containing vibranium. One warrior ingests a "heart-shaped herb" affected by the metal and gains superhuman abilities, becoming the first "Black Panther". He unites all but the Jabari Tribe to form the nation of Wakanda. The Wakandans use the vibranium to develop advanced technology and isolate themselves from the world by posing as a Third World country.
In 1992, King TChaka visits his brother NJobu, who is working undercover in Oakland, California. TChaka accuses NJobu of assisting black-market arms dealer Ulysses Klaue with stealing vibranium from Wakanda. NJobus partner reveals he is Zuri, another undercover Wakandan, and confirms TChakas suspicions.
In the present day, following TChakas death,[N 1] his son TChalla returns to Wakanda to assume the throne. He and Okoye, the leader of the Dora Milaje regiment, extract Nakia, TChallas ex-lover, from an undercover assignment so she can attend his coronation ceremony with his mother Ramonda and younger sister Shuri. At the ceremony, the Jabari Tribes leader MBaku challenges TChalla for the crown in ritual combat. TChalla defeats MBaku and persuades him to yield rather than die.
After Klaue and Erik Stevens steal a Wakandan artifact from a London museum, WKabi, TChalla friend and Okoyes lover, urges him to bring Klaue back dead or alive. TChalla, Okoye, and Nakia travel to Busan, South Korea, where Klaue plans to sell the artifact to CIA agent Everett K. Ross. A firefight erupts and Klaue attempts to flee but is caught by TChalla, who reluctantly releases him to Ross custody. Klaue tells Ross that Wakandas international image is a front for a technologically advanced civilization. Erik attacks and extracts Klaue as Ross is gravely injured protecting Nakia. Rather than pursue Klaue, TChalla takes Ross to Wakanda, where their technology can save him.',0),
  ('TOMB RIDER: LARA CROFT','adventure','2018-03-15','2018-04-11',138,'tombRider.jpg','Lara Croft embarks in his first expedition to finish the job the father of archaeological research and uncover ancient secrets',1),
  ('GHOSTLAND','horror','2018-03-15','2018-03-20',157,'ghostland.jpg','Beth returned to his native place',1),
  ('A WRINKLE IN A TIME','adventure','2018-03-15','2018-04-03',187,'wrinkle.jpg','Young Meg, along with his younger brother and school friend decides to go in search of his father, a physicist, who disappeared in the course of a scientific experiment. To find it is not in the usual world, but in the mysterious fractures of time and space, where the concept of reality is relative and nothing can be believed! Get out of the fantasy worlds and defeat the darkness that spreads through the universe, you can only learn yourself and accept their shortcomings.',1);

